packages:
  - examples/*
  - node
  - wasm

catalog:
  react: ^19.1.0
  react-dom: ^19.1.0
  '@biomejs/biome': ^1.9.4
  '@napi-rs/cli': ^2.18.4
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.2
  '@vitejs/plugin-react': ^4.3.4
  typescript: ^5.8.3
  vite: ^6.2.6
  vitest: ^3.1.1

ignoredBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
