[package]
edition = "2021"
name = "node"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "3.0.0-alpha"
napi-derive = "3.0.0-alpha"
hangul = { path = "../core" }

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
codegen-units = 1
