/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function hangulDisassemble(text: string): string
export declare function hangulGetChoseong(text: string): string
